exp_name : 2-stage

train_path: ./train

ckpt_path:

lr        : 0.0001
epoch     : 50
batch_size: 24
num_worker: 16

log_interval           : 16
log_on_bar_interval    : 16

nlevel  : 18
ntoken  : 256

ninp    : 552
nhid    : 552
nout    : 256
nhead   : 4
nlayers : 4
dropout : 0.0

context_window: 1024

